Repository Onemind-Services-LLC/py-jelastic, pull requests merged in 2024-01, with the labels that each got.

#76 Fixed Billing.Order methods
  jelastic/api/billing/__init__.py
  tests/unit/test_api/test_billing/test_order.py
Labels: type: bug

#80 Settings Parameters Fix
  jelastic/api/marketplace/__init__.py
  tests/unit/test_api/test_marketplace/test_app.py
Labels: type: housekeeping

#82 App ID Added for development.Scripting
  jelastic/api/development/__init__.py
  tests/unit/test_api/test_development/test_scripting.py
  tests/unit/test_api/test_environment/test_control.py
Labels: type: feature

#84 Added ruk parameter
  jelastic/__init__.py
  jelastic/api/abstract.py
  jelastic/api/administration/__init__.py
  jelastic/api/automation/__init__.py
  jelastic/api/billing/__init__.py
  jelastic/api/data/__init__.py
  jelastic/api/development/__init__.py
  jelastic/api/environment/__init__.py
  jelastic/api/iaas/__init__.py
  jelastic/api/io/__init__.py
  jelastic/api/management/__init__.py
  jelastic/api/marketplace/__init__.py
  jelastic/api/message/__init__.py
  jelastic/api/migration/__init__.py
  jelastic/api/platform/__init__.py
  jelastic/api/pool/__init__.py
  jelastic/api/pricing/__init__.py
  jelastic/api/s3/__init__.py
  jelastic/api/security/__init__.py
  jelastic/api/statistic/__init__.py
  jelastic/api/system/__init__.py
  jelastic/api/thirdparty/__init__.py
  jelastic/api/users/__init__.py
  jelastic/api/utils/__init__.py
Labels: type: feature

#86 Made changes in Management,migration,message,marketplace and tests
  jelastic/api/management/__init__.py
  jelastic/api/marketplace/__init__.py
  jelastic/api/message/__init__.py
  jelastic/api/migration/__init__.py
  tests/unit/test_api/test_management/test_account.py
  tests/unit/test_api/test_marketplace/test_admin.py
  tests/unit/test_api/test_marketplace/test_app.py
  tests/unit/test_api/test_marketplace/test_console.py
  tests/unit/test_api/test_marketplace/test_favorite.py
  tests/unit/test_api/test_marketplace/test_installation.py
  tests/unit/test_api/test_marketplace/test_jps.py
  tests/unit/test_api/test_message/test_email.py
  tests/unit/test_api/test_migration/test_migration.py
Labels: type: feature

#87 Update the parameters and params in development, environment, iaas, and io API
  jelastic/api/development/__init__.py
  jelastic/api/environment/__init__.py
  jelastic/api/iaas/__init__.py
  jelastic/api/io/__init__.py
Labels: type: feature
